### ISSUE TITLE
feature request: add German dictionary

### ISSUE THREAD

**Issue by CNurt** [leezu/zhongwen#12]
The German dictionary files from [this ](https://chrome.google.com/webstore/detail/zhongwen-chinesisch-deuts/jjkbnbgakjgfiajfkifdbhbfmjgmddeh?hl=de) Chrome extension works with your firefox addon (tested).

Yet, I'm unable to implement an option for switching between both dictionaries.

Would this be possible?

**Comment by leezu** [comment]
It should be feasible. The only downside is that currently the dictionary data is distributed as part of the addon. Meaning that if more dictionaries are added, the size of the addon increases even though most users only use one of the dictionaries. I believe that is why Chris (who develops the Chrome version) chose to offer two addons.

Would a separate addon work for you? We may still keep both dictionary files in the repository here, but implement a switch to select which dictionary file to package when building the addon? Alternatively, to just use a single addon and give an option to switch I guess it would be best to not distribute the dictionary files with the addon, but download them from some server (which could be the files hosted in this repository on github).

**Comment by CNurt** [comment]
I agree,
Privately I am already using your plugin, altered with the German "hande" dictionary file.

For a separate addon the minimum changes required are the two lines for dictionary file and index.
Additionally, title, description, etc. (Could be copied from [here ](https://chrome.google.com/webstore/detail/zhongwen-chinesisch-deuts/jjkbnbgakjgfiajfkifdbhbfmjgmddeh?hl=de) )

my questions (this is my first time trying to contribute =)  :
1. Is a separate repository required or will a new branch work? (I imagine a new branch would be easier when incorporating updates)
2. If we create a separate repository or branch, who is going to host it?

**Comment by leezu** [comment]
Ok, great. Regarding the difference between creating a new repository compared to a separate branch in this repository, from a development standpoint there is no difference in difficulty. However for end-users or other developers it may be easier to find / contribute the code if we keep everything in a single repository. It may make sense to create a 'zhongwen' organization on Github and keeping the repository there instead of as part of my personal account.

For now I have created a `chrome-german` and `german` branch in this repository. The `chrome-german` branch differs from the `chrome` branch by [overwriting all files](https://github.com/leezu/zhongwen/commit/2e254ecf9b843ef5231caee2dd9c453bbf77c54b) with the ones from the [German version of the Chrome addon](https://chrome.google.com/webstore/detail/zhongwen-chinesisch-deuts/jjkbnbgakjgfiajfkifdbhbfmjgmddeh). The `german` branch is on the state of the "normal" Firefox branch + [merging the changes from `chrome-german`](https://github.com/leezu/zhongwen/commit/2baf2e3c5e4930f1100e81a11cb43c3a1c74ce51), which is mainly localization and change of the dictionary files after telling git to ignore the differences resulting from the refactoring I did for the Firefox release. I submitted the resulting version to the [addon store](https://addons.mozilla.org/en-US/firefox/addon/zhongwen-chinese-german/). I hope this is also fine with you.

I saw you also made some further changes in your branch. Would you like to PR them to the master branch? I suggest to develop always against the master branch and then any changes can be merged to the `german` branch. What do you think?

**Comment by CNurt** [comment]
I go with whatever you suggest. Since I am still learning/fighting with github/git and its different functions.
Although I think that atm there is no need for an organization for this little plugin.

Regarding my fork, since now I mainly used it for experimenting and learning Javascript, WebExtensions & Github. I will PR any relevant changes.

I agree with you to develop non-language-related things against the master branch.
